#!/usr/bin/env bash
set -u

project_root="/Users/wlancer/Coding_Projects/TypesetTranslate/newPapers/build-directories/yin_qft_253abc"
codex_bin="/Applications/ChatGPT.app/Contents/Resources/codex"
lane_root="$project_root/work/253a-ch02/source-lanes"
log_root="$project_root/work/253a-ch02/agent-logs/pass1"
summary_file="$log_root/status.tsv"

mkdir -p "$lane_root" "$log_root"
: > "$summary_file"

task_pids=()
task_labels=()

launch_lane() {
  lane_label="$1"
  lane_prompt="$2"
  shift 2

  "$codex_bin" exec \
    --ephemeral \
    -m gpt-5.6-luna \
    -c 'model_reasoning_effort="max"' \
    -c 'service_tier="priority"' \
    -s workspace-write \
    -C "$project_root" \
    "$@" \
    -- \
    "$lane_prompt" \
    > "$log_root/$lane_label.log" 2>&1 &

  task_pids+=("$!")
  task_labels+=("$lane_label")
}

for first_page in $(seq 21 2 61); do
  second_page=$((first_page + 1))
  first_tag=$(printf '%03d' "$first_page")
  second_tag=$(printf '%03d' "$second_page")
  lane_name="notes-${first_tag}-${second_tag}"
  output_rel="work/253a-ch02/source-lanes/${lane_name}.md"
  first_image="$project_root/tmp/pdfs/253a-ch02-source/page-${first_tag}.png"
  second_image="$project_root/tmp/pdfs/253a-ch02-source/page-${second_tag}.png"
  lane_prompt="Pass 1 full source-capture lane for Xi Yin QFT Chapter 2. Read SOURCE_MANIFEST.yaml, AGENT_POLICY.md, WRITING_STYLE.md, WORKFLOW.md, CHAPTER_PLAN.md, and MASTER_PROMPT.md completely before acting. Inspect combined PDF physical pages ${first_page}-${second_page} through the two attached full-page renders and the source PDF. Capture every recoverable heading, prose fragment, equation, diagram, graph, color, arrow, correction, annotation, example, qualification, original handwritten page label, and page transition. Preserve the source without polishing. Establish exact TeX for every formula and flag uncertain characters. Write only ${output_rel} using apply_patch. Include page-by-page exact transcription, visual semantics, ambiguities, topic boundaries, and recommended dispositions. Do not edit captions, canonical LaTeX, scripts, policies, Chapter 1, or any existing file. Do not spawn agents."
  launch_lane "$lane_name" "$lane_prompt" -i "$first_image" "$second_image"
done

video_specs=(
  "96lN2omwit4:2022-09-06"
  "uzixOflp0tY:2022-09-08"
  "M0py5a4RWhE:2022-09-13"
  "vk_RlYUKUyM:2022-09-15"
  "3VG2kDHso08:2022-09-20"
  "TtMNnZ8__UU:2022-09-22"
  "82__84nYd4I:2022-09-27"
  "ph3wE8cFMmk:2022-09-29"
)

for video_spec in "${video_specs[@]}"; do
  video_id="${video_spec%%:*}"
  video_date="${video_spec##*:}"
  lane_name="video-${video_id}"
  output_rel="work/253a-ch02/source-lanes/${lane_name}.md"
  lane_prompt="Pass 1 full lecture source-capture lane for Xi Yin QFT Chapter 2. Read SOURCE_MANIFEST.yaml, AGENT_POLICY.md, WRITING_STYLE.md, WORKFLOW.md, CHAPTER_PLAN.md, and MASTER_PROMPT.md completely before acting. Examine the complete autogenerated JSON3 and VTT caption tracks under work/253a-ch02/captions for video ${video_id}, recorded ${video_date}. Use the rendered handwritten pages 20-68 and work/pilot/playlist.jsonl to identify source order. Produce a continuous timestamped inventory of every recoverable substantive claim, question, joke, example, qualification, equation reference, board transition, logistics interval, and Q and A interval. Preserve raw wording and mark recognition errors or uncertain speech. Identify exact first and last Chapter 2 timestamps, topic-to-note-page matches, and possible overlap with adjacent lectures. Write only ${output_rel} using apply_patch. Do not polish the transcript, rewrite captions, edit canonical LaTeX, or modify any existing file. Do not spawn agents."
  launch_lane "$lane_name" "$lane_prompt"
done

launch_lane \
  "boundary-assignment" \
  "Pass 1 boundary lane for Xi Yin QFT Chapter 2. Read all six binding project documents. Inspect combined PDF physical pages 20, 62, 63-68 visually and by extraction. Pages 63-67 are assignment material reserved for later integration. Physical page 68 is the next chapter divider. Reconcile these page boundaries against the complete caption tracks for videos TtMNnZ8__UU, 82__84nYd4I, and ph3wE8cFMmk. Determine the exact spoken transition from Chapter 2 to relativistic particles, fields, and Green functions. Record precise timestamps, boundary phrases, page identities, confidence, and dispositions. Write only work/253a-ch02/source-lanes/boundary-assignment.md using apply_patch. Do not edit existing files or canonical LaTeX. Do not spawn agents." \
  -i \
  "$project_root/tmp/pdfs/253a-ch02-source/page-020.png" \
  "$project_root/tmp/pdfs/253a-ch02-source/page-062.png" \
  "$project_root/tmp/pdfs/253a-ch02-source/page-063.png" \
  "$project_root/tmp/pdfs/253a-ch02-source/page-064.png" \
  "$project_root/tmp/pdfs/253a-ch02-source/page-065.png" \
  "$project_root/tmp/pdfs/253a-ch02-source/page-066.png" \
  "$project_root/tmp/pdfs/253a-ch02-source/page-067.png" \
  "$project_root/tmp/pdfs/253a-ch02-source/page-068.png"

launch_lane \
  "playlist-chronology" \
  "Pass 1 lecture-identity lane for Xi Yin QFT Chapter 2. Read all six binding project documents, work/pilot/playlist.jsonl, work/pilot/source-map.md, every Chapter 2 caption track, and the source-page renders for physical pages 20-68. Establish the exact chronological lecture set for handwritten note pages 10-51 and physical pages 20-62. Detect missing, duplicate, or outside-scope recordings. Give exact content boundaries and transition evidence, including the lecture corresponding to physical page 68. Write only work/253a-ch02/source-lanes/playlist-chronology.md using apply_patch. Do not edit existing files or canonical LaTeX. Do not spawn agents."

for task_index in "${!task_pids[@]}"; do
  task_pid="${task_pids[$task_index]}"
  task_label="${task_labels[$task_index]}"
  if wait "$task_pid"; then
    printf '%s\tcomplete\n' "$task_label" >> "$summary_file"
  else
    task_status="$?"
    printf '%s\tfailed:%s\n' "$task_label" "$task_status" >> "$summary_file"
  fi
done
