#!/usr/bin/env python3
"""Build Chapter 2 identity, page-map, playlist, and raw-source metadata."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
WORK = ROOT / "work" / "253a-ch02"
PILOT_PLAYLIST = ROOT / "work" / "pilot" / "playlist.jsonl"
SOURCE_PDF = Path("/Users/wlancer/Desktop/IAS/phy/qft/qft_253abc_book.pdf")
SOURCE_PDF_SHA256 = "9e5e4d241fffffa56c1c3df6dce4b83178f75787dd5d794a18c5d0c087769f21"
PLAYLIST_ID = "PLAd5nTR2YCdoAkJnywB0B9f8cghPSLM9m"

LECTURES = (
    {
        "order": 1,
        "date": "2022-09-06",
        "video_id": "96lN2omwit4",
        "core_start": "00:01:26.700",
        "core_end": "01:20:25.500",
        "note_pages": [10, 14],
        "pdf_pages": [21, 25],
    },
    {
        "order": 2,
        "date": "2022-09-08",
        "video_id": "uzixOflp0tY",
        "core_start": "00:02:50.879",
        "core_end": "01:19:02.520",
        "note_pages": [15, 20],
        "pdf_pages": [26, 31],
    },
    {
        "order": 3,
        "date": "2022-09-13",
        "video_id": "M0py5a4RWhE",
        "core_start": "00:00:02.340",
        "core_end": "01:23:02.640",
        "note_pages": [21, 28],
        "pdf_pages": [32, 39],
    },
    {
        "order": 4,
        "date": "2022-09-15",
        "video_id": "vk_RlYUKUyM",
        "core_start": "00:00:12.660",
        "core_end": "01:18:28.140",
        "note_pages": [29, 37],
        "pdf_pages": [40, 48],
    },
    {
        "order": 5,
        "date": "2022-09-20",
        "video_id": "3VG2kDHso08",
        "core_start": "00:01:10.080",
        "core_end": "01:18:54.780",
        "note_pages": [38, 44],
        "pdf_pages": [49, 55],
    },
    {
        "order": 6,
        "date": "2022-09-22",
        "video_id": "TtMNnZ8__UU",
        "core_start": "00:00:14.179",
        "core_end": "00:51:10.020",
        "note_pages": [45, 51],
        "pdf_pages": [56, 62],
        "close_cue_start": "00:50:22.579",
        "close_cue_end": "00:50:29.280",
        "chapter3_explicit_topic_start": "00:51:15.660",
    },
)

BOUNDARY_VIDEOS = (
    {
        "date": "2022-09-27",
        "video_id": "82__84nYd4I",
        "chapter_role": "chapter3_continuation_boundary_evidence",
        "first_substantive_start": "00:00:26.119",
    },
    {
        "date": "2022-09-29",
        "video_id": "ph3wE8cFMmk",
        "chapter_role": "chapter3_continuation_boundary_evidence",
        "first_substantive_start": "00:00:23.279",
    },
)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def find_caption(video_id: str, suffix: str) -> Path:
    paths = sorted((WORK / "captions").glob(f"*-{video_id}.en.{suffix}"))
    if len(paths) != 1:
        raise RuntimeError(f"expected one {suffix} caption for {video_id}: {paths}")
    return paths[0]


def load_playlist() -> dict[str, dict[str, object]]:
    records = {}
    for line in PILOT_PLAYLIST.read_text(encoding="utf-8").splitlines():
        row = json.loads(line)
        video_id = row.get("video_id")
        if isinstance(video_id, str):
            records.setdefault(video_id, row)
    return records


def raw_source_records(video_id: str) -> list[dict[str, object]]:
    result = []
    for suffix, kind in (("json3", "youtube_autogenerated_json3"), ("vtt", "youtube_autogenerated_vtt")):
        path = find_caption(video_id, suffix)
        result.append(
            {
                "kind": kind,
                "video_id": video_id,
                "path": str(path.relative_to(ROOT)),
                "sha256": sha256(path),
                "bytes": path.stat().st_size,
            }
        )
    video = WORK / "video" / f"{video_id}.mp4"
    if video.is_file():
        result.append(
            {
                "kind": "downloaded_source_video_mp4_format18",
                "video_id": video_id,
                "path": str(video.relative_to(ROOT)),
                "sha256": sha256(video),
                "bytes": video.stat().st_size,
            }
        )
    return result


def compact_jsonl(rows: list[dict[str, object]]) -> str:
    return "".join(
        json.dumps(row, ensure_ascii=False, separators=(",", ":")) + "\n"
        for row in rows
    )


def main() -> None:
    actual_source_hash = sha256(SOURCE_PDF)
    if actual_source_hash != SOURCE_PDF_SHA256:
        raise RuntimeError(
            f"source PDF hash mismatch: {actual_source_hash} != {SOURCE_PDF_SHA256}"
        )

    playlist = load_playlist()
    selected = [*LECTURES, *BOUNDARY_VIDEOS]
    raw_sources: list[dict[str, object]] = []
    playlist_rows: list[dict[str, object]] = [
        {
            "record_type": "chapter_playlist_metadata",
            "schema_version": 2,
            "chapter_id": "253a-ch02",
            "playlist_id": PLAYLIST_ID,
            "chronology_basis": "recorded_at_utc",
            "chapter_video_order": [row["video_id"] for row in LECTURES],
            "boundary_video_order": [row["video_id"] for row in BOUNDARY_VIDEOS],
        }
    ]
    for selection in selected:
        video_id = str(selection["video_id"])
        base = playlist.get(video_id)
        if base is None:
            raise RuntimeError(f"playlist record missing for {video_id}")
        sources = raw_source_records(video_id)
        raw_sources.extend(sources)
        role = (
            "chapter2_core_lecture"
            if "order" in selection
            else selection["chapter_role"]
        )
        playlist_rows.append(
            {
                **base,
                "chapter_id": "253a-ch02",
                "chapter_role": role,
                **{key: value for key, value in selection.items() if key != "chapter_role"},
                "raw_sources": sources,
            }
        )

    page_map: list[dict[str, object]] = [
        {
            "pdf_page": 20,
            "note_page": None,
            "page_kind": "chapter_divider",
            "disposition": "included_structural_boundary",
        }
    ]
    for pdf_page in range(21, 63):
        page_map.append(
            {
                "pdf_page": pdf_page,
                "note_page": pdf_page - 11,
                "page_kind": "handwritten_lecture_note",
                "disposition": "included",
            }
        )

    metadata = {
        "schema_version": 2,
        "chapter_id": "253a-ch02",
        "chapter_number": 2,
        "title": "Lagrangian Quantum Mechanics, Path Integrals, and Perturbation Theory",
        "tex_path": "latex/chapters/253a/chapter02.tex",
        "source_id_prefix": "YIN253A-C02",
        "source_pdf": str(SOURCE_PDF),
        "source_pdf_sha256": SOURCE_PDF_SHA256,
        "physical_pdf_pages": [20, 62],
        "handwritten_note_pages": [10, 51],
        "page_map": page_map,
        "excluded_assignment_pages": {
            "physical_pdf_pages": [63, 67],
            "disposition": "reserved_for_later_assignment_integration",
        },
        "next_chapter_boundary": {
            "physical_pdf_page": 68,
            "title": "Relativistic Particles, Fields, and Green Functions",
            "boundary_video_id": "TtMNnZ8__UU",
            "chapter2_close_cue": ["00:50:22.579", "00:50:29.280"],
            "chapter2_half_open_end": "00:51:10.020",
            "chapter3_explicit_topic_start": "00:51:15.660",
        },
        "endpoint_convention": "[start,end)",
        "video_order": [row["video_id"] for row in LECTURES],
        "chapter_intervals": list(LECTURES),
        "boundary_evidence_videos": list(BOUNDARY_VIDEOS),
        "raw_sources": raw_sources,
        "source_decision_evidence": [
            "work/253a-ch02/source-lanes/playlist-chronology.md",
            "work/253a-ch02/source-lanes/boundary-assignment.md",
            "work/253a-ch02/source-lanes/video-TtMNnZ8__UU.md",
            "tmp/pdfs/253a-ch02-video-boundary/96-0086_7.jpg",
            "tmp/pdfs/253a-ch02-video-boundary/Tt-3070.jpg",
            "tmp/pdfs/253a-ch02-video-boundary/82-0026_1.jpg",
        ],
        "review_status": "pass1_reconciled_pending_freeze",
    }

    (WORK / "chapter-metadata.json").write_text(
        json.dumps(metadata, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    (WORK / "playlist.jsonl").write_text(
        compact_jsonl(playlist_rows), encoding="utf-8"
    )
    print(
        json.dumps(
            {
                "chapter_intervals": len(LECTURES),
                "page_map_records": len(page_map),
                "playlist_records": len(playlist_rows),
                "raw_sources": len(raw_sources),
            },
            indent=2,
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
