from __future__ import annotations

import json
import shutil
from pathlib import Path

from .models import ChunkJob, FigureJob, PaperConfig, WorkspacePaths, WorkspaceStatus
from .paths import ensure_workspace_dirs


MASTER_TEMPLATE = """\\pdfoutput=1
\\documentclass[11pt,a4paper]{{article}}
\\usepackage{{jheppub}}
\\usepackage{{amsthm}}
\\usepackage{{wrapfig}}
\\usepackage{{pgfplots}}
\\usepackage[makeroom]{{cancel}}
\\pgfplotsset{{compat=1.18}}
\\notoc

\\title{{{title}}}
\\author{{TODO\\note{{TODO}}}}
\\affiliation{{TODO}}

\\begin{{document}}
\\maketitle
\\flushbottom

% Generated by typesetTranslate.
% Chunks should be transcribed independently and merged by \\input.

{chunk_inputs}

\\end{{document}}
"""


def copy_source_pdf(source_pdf: Path, destination_pdf: Path) -> None:
    if destination_pdf.exists() and destination_pdf.resolve() == source_pdf.resolve():
        return
    shutil.copy2(source_pdf, destination_pdf)


def write_json(path: Path, payload: dict) -> None:
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")


def write_text(path: Path, text: str) -> None:
    path.write_text(text)


def write_project_config(paths: WorkspacePaths, config: PaperConfig) -> None:
    write_json(paths.project_json, config.to_dict())


def write_state(
    paths: WorkspacePaths,
    status: WorkspaceStatus,
) -> None:
    write_json(paths.state_json, status.to_dict())


def write_page_manifest(paths: WorkspacePaths, payload: list[dict[str, str | int]]) -> None:
    write_json(paths.page_manifest_json, {"pages": payload})


def write_master_tex(
    paths: WorkspacePaths,
    title: str,
    chunk_inputs: list[str],
) -> None:
    body = "\n".join(chunk_inputs) if chunk_inputs else "% No chunk inputs yet."
    paths.master_tex.write_text(MASTER_TEMPLATE.format(title=title, chunk_inputs=body))


def write_chunk_prompt(job: ChunkJob, prompt_text: str) -> None:
    Path(job.prompt_file).write_text(prompt_text)


def write_figure_prompt(job: FigureJob, prompt_text: str) -> None:
    Path(job.prompt_file).write_text(prompt_text)


def write_check_wrapper(paths: WorkspacePaths, job: ChunkJob, title: str) -> None:
    chunk_path = Path(job.output_file).relative_to(paths.root)
    check_path = Path(job.check_file)
    check_path.write_text(
        MASTER_TEMPLATE.format(
            title=title,
            chunk_inputs=f"\\input{{{chunk_path.as_posix()}}}",
        )
    )


def write_job_manifest(path: Path, payload: dict) -> None:
    write_json(path, payload)


def initialize_workspace(paths: WorkspacePaths) -> None:
    ensure_workspace_dirs(paths)
