#!/usr/bin/env python3
"""Render a native PDF and audit its page-inspection evidence.

The renderer writes one PNG for each PDF page under ``work/rendered-output``
and one JSON object for each PNG in a JSONL manifest.  The validator checks the
manifest against the current PDF and, when requested, requires a separate
inspection manifest with an explicit ``inspected: true`` record for every page.
It never creates inspection records.  A reviewer must create those records
after looking at the rendered pages.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import struct
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_DIR = ROOT / "work" / "rendered-output"
DEFAULT_MANIFEST = DEFAULT_OUTPUT_DIR / "manifest.jsonl"
DEFAULT_INSPECTION_MANIFEST = ROOT / "work" / "reviews" / "page-inspection.jsonl"
DEFAULT_DPI = 180
PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"
PAGE_FILE_RE = re.compile(r"^page-(\d+)\.png$")


def pdf_page_count(pdf: Path) -> int:
    result = subprocess.run(
        ["pdfinfo", str(pdf)], check=True, capture_output=True, text=True
    )
    match = re.search(r"^Pages:\s+(\d+)\s*$", result.stdout, re.MULTILINE)
    if match is None:
        raise SystemExit(f"Could not read page count from {pdf}")
    return int(match.group(1))


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def png_dimensions(path: Path) -> tuple[int, int]:
    with path.open("rb") as handle:
        header = handle.read(24)
    if len(header) != 24 or header[:8] != PNG_SIGNATURE:
        raise ValueError(f"Not a PNG with a readable IHDR header: {path}")
    width, height = struct.unpack(">II", header[16:24])
    if width <= 0 or height <= 0:
        raise ValueError(f"PNG has invalid dimensions: {path}")
    return width, height


def generated_pages(output_dir: Path) -> dict[int, Path]:
    pages: dict[int, Path] = {}
    for path in sorted(output_dir.glob("page-*.png")):
        match = PAGE_FILE_RE.fullmatch(path.name)
        if match is None:
            continue
        page = int(match.group(1))
        if page in pages:
            raise SystemExit(f"Duplicate rendered page number {page} in {output_dir}")
        pages[page] = path
    return pages


def render(pdf: Path, output_dir: Path, manifest: Path, dpi: int) -> int:
    if not pdf.is_file():
        raise SystemExit(f"Missing compiled PDF: {pdf}")
    if dpi <= 0:
        raise SystemExit("DPI must be positive")
    output_dir.mkdir(parents=True, exist_ok=True)
    # Remove only files generated by this script.  Review records live outside
    # this directory and remain untouched.
    for path in output_dir.glob("page-*.png"):
        if PAGE_FILE_RE.fullmatch(path.name):
            path.unlink()
    manifest.parent.mkdir(parents=True, exist_ok=True)

    prefix = output_dir / "page"
    subprocess.run(
        ["pdftoppm", "-png", "-r", str(dpi), str(pdf), str(prefix)], check=True
    )
    pages = generated_pages(output_dir)
    count = pdf_page_count(pdf)
    expected = set(range(1, count + 1))
    if set(pages) != expected:
        missing = sorted(expected - set(pages))
        extra = sorted(set(pages) - expected)
        raise SystemExit(
            "Rendered page set does not match the PDF: "
            f"missing={missing}, extra={extra}"
        )

    records: list[dict[str, object]] = []
    for page in range(1, count + 1):
        path = pages[page]
        width, height = png_dimensions(path)
        records.append(
            {
                "pdf_page": page,
                "filename": path.name,
                "width_px": width,
                "height_px": height,
                "sha256": sha256(path),
                "dpi": dpi,
            }
        )
    manifest.write_text(
        "".join(json.dumps(record, sort_keys=True) + "\n" for record in records),
        encoding="utf-8",
    )
    print(f"Rendered pages: {count}")
    print(f"Rendered output: {output_dir}")
    print(f"Page manifest: {manifest}")
    return 0


def read_jsonl(path: Path) -> list[dict[str, object]]:
    if not path.is_file():
        raise SystemExit(f"Missing JSONL manifest: {path}")
    records: list[dict[str, object]] = []
    for line_number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if not raw.strip():
            continue
        try:
            record = json.loads(raw)
        except json.JSONDecodeError as error:
            raise SystemExit(f"{path}:{line_number}: invalid JSON: {error}") from error
        if not isinstance(record, dict):
            raise SystemExit(f"{path}:{line_number}: each record must be a JSON object")
        records.append(record)
    return records


def validate(
    pdf: Path,
    output_dir: Path,
    manifest: Path,
    inspection_manifest: Path | None,
    require_inspection: bool,
) -> int:
    if not pdf.is_file():
        raise SystemExit(f"Missing compiled PDF: {pdf}")
    count = pdf_page_count(pdf)
    records = read_jsonl(manifest)
    pages: dict[int, dict[str, object]] = {}
    failures: list[str] = []
    for index, record in enumerate(records, 1):
        raw_page = record.get("pdf_page")
        try:
            page = int(raw_page)
        except (TypeError, ValueError):
            failures.append(f"{manifest}:{index}: missing integer pdf_page")
            continue
        if page in pages:
            failures.append(f"{manifest}:{index}: duplicate PDF page {page}")
        pages[page] = record
        if not 1 <= page <= count:
            failures.append(f"{manifest}:{index}: PDF page {page} is outside 1--{count}")
        filename = record.get("filename")
        if not isinstance(filename, str) or PAGE_FILE_RE.fullmatch(filename) is None:
            failures.append(f"{manifest}:{index}: invalid rendered filename {filename!r}")
            continue
        expected_path = output_dir / filename
        if not expected_path.is_file():
            failures.append(f"{manifest}:{index}: missing rendered file {expected_path}")
            continue
        try:
            width, height = png_dimensions(expected_path)
        except ValueError as error:
            failures.append(str(error))
            continue
        if record.get("width_px") != width or record.get("height_px") != height:
            failures.append(f"{manifest}:{index}: dimensions changed for {filename}")
        recorded_hash = record.get("sha256")
        if recorded_hash != sha256(expected_path):
            failures.append(f"{manifest}:{index}: checksum changed for {filename}")

    expected_pages = set(range(1, count + 1))
    if set(pages) != expected_pages:
        failures.append(
            f"Page manifest must contain exactly {count} pages; "
            f"missing={sorted(expected_pages - set(pages))}, "
            f"extra={sorted(set(pages) - expected_pages)}"
        )
    rendered = generated_pages(output_dir)
    if set(rendered) != expected_pages:
        failures.append(
            f"Rendered PNG set must contain exactly {count} pages; "
            f"missing={sorted(expected_pages - set(rendered))}, "
            f"extra={sorted(set(rendered) - expected_pages)}"
        )

    if require_inspection:
        if inspection_manifest is None:
            failures.append("Strict inspection validation requires an inspection manifest")
        elif not inspection_manifest.is_file():
            failures.append(f"Missing page inspection manifest: {inspection_manifest}")
        else:
            inspections = read_jsonl(inspection_manifest)
            manifest_hash = sha256(manifest)
            compiled_pdf_hash = sha256(pdf)
            inspected_pages: dict[int, dict[str, object]] = {}
            for index, record in enumerate(inspections, 1):
                raw_page = record.get("pdf_page")
                try:
                    page = int(raw_page)
                except (TypeError, ValueError):
                    failures.append(
                        f"{inspection_manifest}:{index}: missing integer pdf_page"
                    )
                    continue
                if page in inspected_pages:
                    failures.append(
                        f"{inspection_manifest}:{index}: duplicate PDF page {page}"
                    )
                inspected_pages[page] = record
                if page not in expected_pages:
                    failures.append(
                        f"{inspection_manifest}:{index}: PDF page {page} is outside 1--{count}"
                    )
                if record.get("inspected") is not True:
                    failures.append(
                        f"{inspection_manifest}:{index}: PDF page {page} is not marked inspected"
                    )
                rendered_hash = record.get("rendered_sha256")
                if not isinstance(rendered_hash, str) or not rendered_hash:
                    failures.append(
                        f"{inspection_manifest}:{index}: PDF page {page} lacks rendered_sha256"
                    )
                elif pages.get(page, {}).get("sha256") != rendered_hash:
                    failures.append(
                        f"{inspection_manifest}:{index}: rendered checksum mismatch for PDF page {page}"
                    )
                if record.get("render_manifest_sha256") != manifest_hash:
                    failures.append(
                        f"{inspection_manifest}:{index}: render-manifest checksum mismatch for PDF page {page}"
                    )
                if record.get("pdf_sha256") != compiled_pdf_hash:
                    failures.append(
                        f"{inspection_manifest}:{index}: compiled-PDF checksum mismatch for PDF page {page}"
                    )
                reviewer = record.get("reviewer")
                if not isinstance(reviewer, str) or not reviewer.strip():
                    failures.append(
                        f"{inspection_manifest}:{index}: PDF page {page} lacks reviewer"
                    )
                inspected_at = record.get("inspected_at")
                if not isinstance(inspected_at, str) or not inspected_at.strip():
                    failures.append(
                        f"{inspection_manifest}:{index}: PDF page {page} lacks inspected_at"
                    )
                observation = record.get("observation")
                if not isinstance(observation, str) or not observation.strip():
                    failures.append(
                        f"{inspection_manifest}:{index}: PDF page {page} lacks observation"
                    )
            if set(inspected_pages) != expected_pages:
                failures.append(
                    f"Inspection manifest must contain exactly {count} pages; "
                    f"missing={sorted(expected_pages - set(inspected_pages))}, "
                    f"extra={sorted(set(inspected_pages) - expected_pages)}"
                )

    if failures:
        print("RELEASE EVIDENCE AUDIT FAILURES", file=sys.stderr)
        for failure in failures:
            print(f"  - {failure}", file=sys.stderr)
        return 1
    print(f"Release evidence validated for {count} PDF pages")
    if require_inspection:
        print(f"Page inspection manifest: {inspection_manifest}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    render_parser = subparsers.add_parser("render")
    render_parser.add_argument("--input", dest="pdf", type=Path, required=True)
    render_parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    render_parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    render_parser.add_argument("--dpi", type=int, default=DEFAULT_DPI)

    validate_parser = subparsers.add_parser("validate")
    validate_parser.add_argument("--input", dest="pdf", type=Path, required=True)
    validate_parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    validate_parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    validate_parser.add_argument(
        "--inspection-manifest", type=Path, default=DEFAULT_INSPECTION_MANIFEST
    )
    validate_parser.add_argument("--require-inspection", action="store_true")

    args = parser.parse_args()
    if args.command == "render":
        return render(args.pdf, args.output_dir, args.manifest, args.dpi)
    return validate(
        args.pdf,
        args.output_dir,
        args.manifest,
        args.inspection_manifest,
        args.require_inspection,
    )


if __name__ == "__main__":
    raise SystemExit(main())
